name: Latency
main: com.github.neapovil.latency.Latency
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/latency
depend:
  - CommandAPI
permissions:
  latency.command.self:
    default: true
  latency.command.other:
    default: true
